### ISSUE TITLE
图片粘贴事件不生效

### ISSUE THREAD

**Issue by 0xbing** [zhaoxuhui1122/vue-markdown#10]
`<template>
	<MarkDown @on-paste-image="test"  >
	</MarkDown>
</template>

<script>
	import MarkDown from 'vue-meditor';
	export default {
		data() {
		    return { }
		},
		mounted() {
			
		},
		methods:{
			test(){
				console.log("test");
				return
			}
		},
		components:{
			MarkDown
		},
	}
</script>

<style>
</style>
`
绑定on-paste-image功能，不生效，这个是怎么回事？？

**Comment by zhaoxuhui1122** [comment]
我本地试了一下，暂时没发现问题，可以正常触发事件，可以查看一下组件内markdown.js内handlePaste这个方法，可能是兼容问题

**Comment by Linya-Coder** [comment]
我也尝试了一下on-upload-image事件，不管我怎么粘贴图片都不会触发。工具栏中的上传按钮我也没有找到，哪怕添加了uploadImage属性。
