### ISSUE TITLE
marked 能否暴露出 baseUrl 属性

### ISSUE THREAD

**Issue by dkvirus** [zhaoxuhui1122/vue-markdown#12]
# 问题

目前 markdown 里的图片只能用网络地址，不能用本地路径引用图片。在 marked issues 里发现有 baseUrl 属性，可以给 img 路径添加前缀，可以解决这个问题。

```
marked.setOptions({
  baseUrl: 'http://example.com/',
});
```

markdown 写法

```
![](static/cat.svg)
```

目前输出

```
<p><img src="/static/cat.svg" alt=""></p>
```

期待输出

```
<p><img src="http://example.com/static/cat.svg" alt=""></p>
```

# 建议

vue 组件暴露属性 `markedOptions`，用户可以自定义 marked 语法。

**Comment by zhaoxuhui1122** [comment]
好的，我接下来研究一下，多谢提出问题

**Comment by zhaoxuhui1122** [comment]
请求已经合并，关于上传时忽略文件夹的问题，npm发布时已忽略，git上传时之所以要保留dist文件夹，是因为示例直接运行需要里面的文件
