### ISSUE TITLE
图片不生效的几个问题

### ISSUE THREAD

**Issue by kenasel** [zhaoxuhui1122/vue-markdown#14]
1.代码中指定路径的图片不生效，而使用外链就可以
2.图片粘贴事件是有正常输出文件，但是页面没显示，是不是本来就是这样的
![image](https://user-images.githubusercontent.com/18522653/59986599-15536f00-966a-11e9-9923-a9a81e0a1f53.png)

**Comment by zhaoxuhui1122** [comment]
目前是不支持这么写的，在考虑定义图片的baseUrl，参考#12](https://github.com/zhaoxuhui1122/vue-markdown/issues/12)，目前正在开发，稍后测试完通知
