### ISSUE TITLE
怎么显示markdown内容

### ISSUE THREAD

**Issue by GeeRobin** [zhaoxuhui1122/vue-markdown#16]
刚看完Vue基本语法（苦逼的后端），对Vue还不是很熟。
目前我的问题是，我数据库里有很多markwodn格式的内容，在前端要将它们显示成html，不知道本插件有没有提供一个函数或组件来解析marldown内容。

**Comment by zhaoxuhui1122** [comment]
如果只是为了展示markdown格式的内容，建议直接写一个解析组件，这个毕竟是一个编辑器，分量略重，解析的话也是依赖marked.js和highlight.js解析
