### ISSUE TITLE
设置主题没反应

### ISSUE THREAD

**Issue by iPenManShip** [zhaoxuhui1122/vue-markdown#17]
![image](https://user-images.githubusercontent.com/36189354/61171751-91c4d800-a5ae-11e9-90ea-10b4b31d6b96.png)
![image](https://user-images.githubusercontent.com/36189354/61171757-a43f1180-a5ae-11e9-8bd7-2e3e5ebb4491.png)

**Comment by zhaoxuhui1122** [comment]
主题只针对代码块有效，我让确定了一下，代码块主题设置值可以正常切换
