### ISSUE TITLE
能不能支持一下数学符号,流程图这样的,或者说个人开发如何支持

### ISSUE THREAD

**Issue by 1980744819** [zhaoxuhui1122/vue-markdown#2]

**Comment by coinsuper** [comment]
1.  关于支持数学符号，这个之前我没去研究解决方案，我会去抽时间关注一下
2. 关于支持流程图、甘特图之类的功能，最初是有开发的，考虑到许引入第三方js库，增加组件体积，最后把它去掉了，实现思路为：
以甘测图为例：

编辑甘特图，可结合flowchart.js实现，其实也是插入了一段代码块，指定代码块的语言类型，在marked.js内renderer过程定义code渲染方式，如果是甘特图，执行flowchart.js的方法，并返回渲染结果
