### ISSUE TITLE
请问怎么将本地的图片放在文本中

### ISSUE THREAD

**Issue by kongkongya** [zhaoxuhui1122/vue-markdown#23]
拖拽的话 会默认执行浏览器的 查看图片功能 用户想拉取本地的照片放入文本 这个组件中相对应的钩子函数或者事件吗？ 谢谢

**Comment by zhaoxuhui1122** [comment]
暂时不支持，考虑到目前没有接入图片服务器，即使实现了拖拽，也只能本地预览，获取内容详情并上传时无法处理（不建议图片转base64插入内容）
