### ISSUE TITLE
如何在App.vue中拿到MarkDown对应的引用

### ISSUE THREAD

**Issue by yinzhidong** [zhaoxuhui1122/vue-markdown#24]
![image](https://user-images.githubusercontent.com/22864444/64004208-60916e80-cb40-11e9-9399-9c2ff9fdffe5.png)

![image](https://user-images.githubusercontent.com/22864444/64004320-9e8e9280-cb40-11e9-8555-b9868acc769c.png)

获取markdown的引用为undefined。请问该如何获取？

**Comment by zhaoxuhui1122** [comment]
引用后有加入components中吗
