### ISSUE TITLE
请问我只想用那个显示的功能不要编辑器要怎么弄

### ISSUE THREAD

**Issue by yah0130** [zhaoxuhui1122/vue-markdown#25]

**Comment by gytai** [comment]
同问 默认只要显示的怎么配置呢

**Comment by yah0130** [comment]
> 同问 默认只要显示的怎么配置呢

我后来直接用样式把它隐藏了。。。哈哈哈哈

**Comment by lxchinesszz** [comment]
> > 同问 默认只要显示的怎么配置呢
> 
> 我后来直接用样式把它隐藏了。。。哈哈哈哈


 .markdown {
    margin-top: 10px;
    text-align: left;
  }
  .markdown >>> .markdown-toolbars {
    display: none;
  }

  .markdown >>> .markdown-content {
    /*display: none;*/
  }

  .markdown >>> .markdown-editor {
    display: none;
  }

  .markdown >>> .empty {
    display: none;
  }
这样吗？ 貌似没用，是不是语法错了，帮忙看看

**Comment by zhaoxuhui1122** [comment]
已经支持，配置见文档，isPreview属性

**Comment by lxchinesszz** [comment]
强,感谢作者。





在 2019-10-28 14:43:32，"zhaoxuhui" <notifications@github.com> 写道：


已经支持，配置见文档，isPreview属性
