### ISSUE TITLE
关于on-save事件

### ISSUE THREAD

**Issue by Wlisfes** [zhaoxuhui1122/vue-markdown#5]
请问@on-save="save"手动触发该如何去触发这个事件？

**Comment by Wlisfes** [comment]
可能我说的不是太明确，就是我怎么去手动保存的？

**Comment by Wlisfes** [comment]
您好！我看了一下源码，发现子组件里面有个handleSave方法，现在已经解决了，感谢您开源的这个项目！

**Comment by zhaoxuhui1122** [comment]
感谢关注，最近加班厉害，没能及时关注问题，表示抱歉
