### ISSUE TITLE
1.2版本的theme主题设置不生效

### ISSUE THREAD

**Issue by Wlisfes** [zhaoxuhui1122/vue-markdown#8]
我想要像你的说明文件那样黑白的那种代码块，但是貌似设置:theme="OneDark"也不生效，请问是如何设置的呢？

**Comment by Wlisfes** [comment]
请问要是保存htmlValue到页面去显示需要什么css文件才能显示黑色背景的那种代码块呢？

**Comment by zhaoxuhui1122** [comment]
已经修复了，重写编辑器时除了点儿问题，多谢指正，可以看一下目前示例，v.12.1
